%% Horizontal Use Case Diagram
graph LR
    B(Reader)
    B --> 1(Create a reader account)
    B --> 2(Login to a reader)
    B --> 3(Get all reader)
    B --> C

    C(Book) --> 4(Get all books)
    C --> 5(Search for a book)
    C --> 7(Borrow a book)
    C --> 8(Return a book)

